// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PZServerLauncher.Host.Data;

#nullable disable

namespace PZServerLauncher.Host.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408153000_AddNamedWorkshopPresets")]
    partial class AddNamedWorkshopPresets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotProxy().Apply(modelBuilder);
        }

        private sealed class SnapshotProxy : ApplicationDbContextModelSnapshot
        {
            public void Apply(ModelBuilder modelBuilder)
            {
                BuildModel(modelBuilder);
            }
        }
    }
}
